version: 2.0

workflows:
  version: 2

  commit-workflow:
    jobs:
      - selenium/run
  
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * 1-3"
          filters:
            branches:
              only:
                - main
    jobs:
      - selenium/run

jobs:
  selenium/run:
    docker:
      - image: cimg/python:3.8.13-browsers
    steps:
      - checkout
      - curl https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip | gzip -dc > chromedriver
      - chmod +x chromedriver
      - google-chrome --version
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main" >> /etc/apt/sources.list.d/google.list'
      - sudo apt-get update
      - sudo apt-get --only-upgrade install google-chrome-stable
      - google-chrome --version
      - run: poetry install
      - run:
          name: e2e test
          command: poetry run pytest -v
 