version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: poetry install
      - run:
          name: e2e test
          command: poetry run pytest -v