version: 2.0

workflows:
  version: 2

  commit-workflow:
    jobs:
      - selenium/run
  
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * 1-3"
          filters:
            branches:
              only:
                - main
    jobs:
      - selenium/run

jobs:
  selenium/run:
    docker:
      - image: cimg/python:3.8.13-browsers
    steps:
      - checkout
      - run: poetry install
      - run:
          name: e2e test
          command: pytest -s app/sauce_demo.py
