version: 2.0

workflows:
  version: 2

  commit-workflow:
    jobs:
      - selenium/run
  
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * 1-3"
          filters:
            branches:
              only:
                - main
    jobs:
      - selenium/run

jobs:
  selenium/run:
    docker:
      - image: cimg/python:3.8.13-browsers
    steps:
      - checkout
      - run: curl https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip | gzip -dc > chromedriver
      - run: chmod +x chromedriver
      - run: sudo ln -s 'which chromedriver' /usr/local/bin/chromedriver
      - run: poetry install
      - run:
          name: e2e test
          command: poetry run pytest -v
 